/* eslint */

'use strict';

module.exports = {
  dist: './_dist',
  libdir: './lib',
  libname: 'overslash',
  parent: 'this',
  // These are the Javascript files required to build the library.
  src: {
    core: [
      './src/_header',
      './src/core.js',
      './src/primitives.js',
      './src/objects.js',
      './src/_footer',
    ],
    obj: [
      './src/_header',
      './src/core.js',
      './src/primitives.js',
      './src/objects.js',
      './src/objectsOps.js',
      './src/arraysOps.js',
      './src/functions.js',
      './src/_footer',
    ],
    tok: [
      './src/_header',
      './src/core.js',
      './src/primitives.js',
      './src/objects.js',
      './src/objectsOps.js',
      './src/arraysOps.js',
      './src/functions.js',
      './src/tokens.js',
      './src/_footer',
    ],
    csv: [
      './src/_header',
      './src/core.js',
      './src/primitives.js',
      './src/objects.js',
      './src/objectsOps.js',
      './src/arraysOps.js',
      './src/functions.js',
      './src/tokens.js',
      './src/csv.js',
      './src/_footer',
    ],
    full: [
      './src/_header',
      './src/core.js',
      './src/primitives.js',
      './src/objects.js',
      './src/objectsOps.js',
      './src/arraysOps.js',
      './src/functions.js',
      './src/tokens.js',
      './src/csv.js',
      './src/_footer',
    ],
  },
  license: ['/** ****************************************************************************',
    ' * {{lib:name}} v{{lib:version}}',
    ' *',
    ' * A tiny modular Javascript utility library.',
    ' * (you can download it from npm or github repositories)',
    ' * Copyright (c) 2017 Jclo <jclo@mobilabs.fr> (http://www.mobilabs.fr).',
    ' * Released under the MIT license. You may obtain a copy of the License',
    ' * at: http://www.opensource.org/licenses/mit-license.php).',
    ' * ****************************************************************************/',
    ''].join('\n'),
};
