/*! ****************************************************************************
 * Overslash v1.0.4
 *
 * A tiny modular Javascript utility library.
 * (you can download it from npm or github repositories)
 * Copyright (c) 2020 Mobilabs <contact@mobilabs.fr> (http://www.mobilabs.fr).
 * Released under the MIT license. You may obtain a copy of the License
 * at: http://www.opensource.org/licenses/mit-license.php).
 * Built from ES6lib v1.0.0-beta.7.
 * ************************************************************************** */
const $__ES6GLOB={};!function(t,e){"use strict";"function"==typeof define&&define.amd?define([""],e):"object"==typeof exports?module.exports=e(t):t.Overslash=e(t)}($__ES6GLOB,t=>{"use strict";let e,r;return r=function(t,e){const r=Object.keys(e);for(let o=0;o<r.length;o++)t[r[o]]=e[r[o]]},function(){const r=t.Overslash;e={library:{name:"Overslash",version:"1.0.4"},_setTestMode:()=>[],noConflict(){return t.Overslash=r,this}},e.VERSION="1.0.4"}(),r(e,{isUndefined:t=>void 0===t,isNull:t=>null===t,isBoolean:t=>!0===t||!1===t||"[object Boolean]"===Object.prototype.toString.call(t),isString:t=>"[object String]"===Object.prototype.toString.call(t),isNumber:t=>"[object Number]"===Object.prototype.toString.call(t),isNaN(t){return this.isNumber(t)&&t!==+t},isOdd(t){const e=t%2;return t===parseFloat(t)?!!e:void 0}}),r(e,{isObject(t){const e=typeof t;return("function"===e||"object"===e)&&!!t},isLiteralObject:t=>"[object Object]"===Object.prototype.toString.call(t),isFunction:t=>"[object Function]"===Object.prototype.toString.call(t),isArray:t=>"[object Array]"===Object.prototype.toString.call(t),isMath:t=>"[object Math]"===Object.prototype.toString.call(t),isDate:t=>"[object Date]"===Object.prototype.toString.call(t),isEmpty(t){let e;if(null===t)return!0;if(this.isArray(t)||this.isString(t))return 0===t.length;for(e in t)if(t.hasOwnProperty(e))return!1;return!0}}),r(e,{}),r(e,{token:()=>Math.random().toString(36).substr(2),makeid(t){const e=this.isNumber(t)?t:16,r="0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz";let o="";for(let t=0;t<e;t++)o+=r.charAt(Math.floor(Math.random()*r.length));return o}}),r(e,{csv2array(t,e){let r,o,n,i;if(!t)throw new Error("The csv line argument is missing!");if("string"!=typeof t)throw new Error("The csv line argument is not a string!");(!e||"string"!=typeof e||e.length>1)&&(e=","),i=0,o=0,n=t.charAt(i);const s=[];for(;""!==n;){for(;" "===n||"\t"===n||"\r"===n;)n=t.charAt(++i);if(r="",'"'===n){n=t.charAt(++i);do{if('"'!==n&&(r+=n,n=t.charAt(++i)),'"'===n)do{if('"'!==t.charAt(i+1))break;r+='"',i+=2,n=t.charAt(i)}while('"'===n)}while(""!==n&&'"'!==n);if(""===n)throw new Error("Unexpected end of data, double-quote expected!");n=t.charAt(++i)}else{for(;""!==n&&n!==e&&"\n"!==n&&" "!==n&&"\t"!==n&&"\r"!==n;)r+=n,n=t.charAt(++i);r.length>0&&(r=parseFloat(r,10))}for(s.length<=o&&s.push([]),s[o].push(r);" "===n||"\t"===n||"\r"===n;)n=t.charAt(++i);if(n===e);else if("\n"===n)o+=1;else if(""!==n)throw new Error("Delimeter expected after character "+i);n=t.charAt(++i)}return s}}),r(e,{delay(t,e,...r){setTimeout(()=>{t(...r)},e)},inRange(t,e,r){let o=e,n=r;return n||(n=e,o=0),t>=o&&t<=n}}),e});export default $__ES6GLOB.Overslash;